### ISSUE TITLE
crash bug

### ISSUE THREAD

**Issue by simpleton** [flike/kingshard#112]
```
[ClientConn] "handleQuery" "runtime error: invalid memory address or nil pointer dereference" "stack=goroutine 77 [running]:
github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery.func1(0xc820417c80)
        /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn_query.go:42 +0x255
github.com/flike/kingshard/proxy/server.(*ClientConn).GetTransExecDB(0xc8201586c0, 0xc8203d26f0, 0x1, 0x1, 0xc8203d26e1, 0x6, 0x1, 0x0, 0x0)
        /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn_preshard.go:111 +0x279
github.com/flike/kingshard/proxy/server.(*ClientConn).preHandleShard(0xc8201586c0, 0xc8203d26e1, 0x6, 0x0, 0x0, 0x0)
        /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn_preshard.go:49 +0x18a
github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery(0xc8201586c0, 0xc8203d26e1, 0x6, 0x0, 0x0)
        /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn_query.go:53 +0xec
github.com/flike/kingshard/proxy/server.(*ClientConn).dispatch(0xc8201586c0, 0xc8203d26e1, 0x6, 0x6, 0x0, 0x0)
        /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn.go:310 +0x564
github.com/flike/kingshard/proxy/server.(*ClientConn).Run(0xc8201586c0)
        /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn.go:286 +0xcd
github.com/flike/kingshard/proxy/server.(*Server).onConn(0xc82009a510, 0x7f8d8647b928, 0xc8201301c0)
        /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/server.go:249 +0x35a
created by github.com/flike/kingshard/proxy/server.(*Server).Run
        /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/server.go:262 +0x195
|sql=commit" conn_id=0
```

**Comment by flike** [comment]
3Q, I'll fix this bug as soon as possible.
