### ISSUE TITLE
Can't begin transcation in commit `4277e29` (latest one)

### ISSUE THREAD

**Issue by simpleton** [flike/kingshard#113]
```
2015/12/31 20:58:07 - ERROR - conn_query.go:[46] - [ClientConn] "handleQuery" "runtime error: invalid memory address or nil pointer dereference" "stack=goroutine 143 [running]:
github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery.func1(0xc82045bc80)
    /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn_query.go:42 +0x255
github.com/flike/kingshard/proxy/server.(*ClientConn).GetTransExecDB(0xc8202046c0, 0xc82027ae00, 0x1, 0x1, 0xc82027adf1, 0x6, 0x1, 0x0, 0x0)
    /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn_preshard.go:111 +0x279
github.com/flike/kingshard/proxy/server.(*ClientConn).preHandleShard(0xc8202046c0, 0xc82027adf1, 0x6, 0x0, 0x0, 0x0)
    /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn_preshard.go:49 +0x18a
github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery(0xc8202046c0, 0xc82027adf1, 0x6, 0x0, 0x0)
    /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn_query.go:53 +0xec
github.com/flike/kingshard/proxy/server.(*ClientConn).dispatch(0xc8202046c0, 0xc82027adf1, 0x6, 0x6, 0x0, 0x0)
    /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn.go:310 +0x564
github.com/flike/kingshard/proxy/server.(*ClientConn).Run(0xc8202046c0)
    /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn.go:286 +0xcd
github.com/flike/kingshard/proxy/server.(*Server).onConn(0xc8200c2630, 0x7fe78fc4e130, 0xc8201841b8)
    /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/server.go:249 +0x35a
created by github.com/flike/kingshard/proxy/server.(*Server).Run
    /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/server.go:262 +0x195
|sql=commit" conn_id=0
2015/12/31 20:58:15 - ERROR - conn_query.go:[46] - [ClientConn] "handleQuery" "runtime error: invalid memory address or nil pointer dereference" "stack=goroutine 126 [running]:
github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery.func1(0xc82052fc80)
    /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn_query.go:42 +0x255
github.com/flike/kingshard/proxy/server.(*ClientConn).GetTransExecDB(0xc8202c4900, 0xc8200125c0, 0x1, 0x1, 0xc8200125b1, 0x6, 0x1, 0x0, 0x0)
    /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn_preshard.go:111 +0x279
github.com/flike/kingshard/proxy/server.(*ClientConn).preHandleShard(0xc8202c4900, 0xc8200125b1, 0x6, 0x0, 0x0, 0x0)
    /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn_preshard.go:49 +0x18a
github.com/flike/kingshard/proxy/server.(*ClientConn).handleQuery(0xc8202c4900, 0xc8200125b1, 0x6, 0x0, 0x0)
    /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn_query.go:53 +0xec
github.com/flike/kingshard/proxy/server.(*ClientConn).dispatch(0xc8202c4900, 0xc8200125b1, 0x6, 0x6, 0x0, 0x0)
    /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn.go:310 +0x564
github.com/flike/kingshard/proxy/server.(*ClientConn).Run(0xc8202c4900)
    /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn.go:286 +0xcd
github.com/flike/kingshard/proxy/server.(*Server).onConn(0xc8200c2630, 0x7fe78fc4e130, 0xc8200821e8)
    /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/server.go:249 +0x35a
created by github.com/flike/kingshard/proxy/server.(*Server).Run
    /home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/server.go:262 +0x195
|sql=commit" conn_id=0
2015/12/31 20:59:06 - ERROR - conn_query.go:[55] - [server] "preHandleShard" "ERROR 1205 (HY000): Lock wait timeout exceeded; try restarting transaction" "hasHandled=false" conn_id=0
2015/12/31 20:59:06 - ERROR - conn.go:[289] - [server] "Run" "ERROR 1205 (HY000): Lock wait timeout exceeded; try restarting transaction" "" conn_id=10086
2015/12/31 20:59:07 - ERROR - conn_query.go:[55] - [server] "preHandleShard" "ERROR 1205 (HY000): Lock wait timeout exceeded; try restarting transaction" "hasHandled=false" conn_id=0
2015/12/31 20:59:07 - ERROR - conn.go:[289] - [server] "Run" "ERROR 1205 (HY000): Lock wait timeout exceeded; try restarting transaction" "" conn_id=10087
2015/12/31 21:00:06 - ERROR - conn_query.go:[55] - [server] "preHandleShard" "ERROR 1205 (HY000): Lock wait timeout exceeded; try restarting transaction" "hasHandled=false" conn_id=0
2015/12/31 21:00:06 - ERROR - conn.go:[289] - [server] "Run" "ERROR 1205 (HY000): Lock wait timeout exceeded; try restarting transaction" "" conn_id=10083
2015/12/31 21:00:10 - INFO - main.go:[108] - [main] "main" "Got signal" "signal=terminated" conn_id=0
```

**Comment by flike** [comment]
OK, I have fixed this bug, please check it.

**Comment by simpleton** [comment]
cool, you guys are awesome. 
Happy New Year~
