### ISSUE TITLE
 ERROR - conn.go:[263] - [ClientConn] "Run" "runtime error: index out of range" "stack=goroutine 35 [running]:

### ISSUE THREAD

**Issue by luyaotang** [flike/kingshard#398]
2017/11/16 17:38:24 - INFO - main.go:[128] - [main] "main" "Got signal" "signal=interrupt" conn_id=0
2017/11/16 17:38:26 - INFO - server.go:[281] - [server] "NewServer" "Server running" "netProto=tcp|address=0.0.0.0:3309" conn_id=0
2017/11/16 17:38:26 - INFO - server.go:[49] - [web] "NewApiServer" "Api Server running" "netProto=http|address=0.0.0.0:3319" conn_id=0
2017/11/16 17:38:33 - ERROR - conn.go:[263] - [ClientConn] "Run" "runtime error: index out of range" "stack=goroutine 35 [running]:
github.com/flike/kingshard/proxy/server.(*ClientConn).Run.func1(0x11490000)
	C:/Go/src/github.com/flike/kingshard/proxy/server/conn.go:259 +0xb3
panic(0x70c540, 0x8f18a0)
	C:/Go/src/runtime/panic.go:489 +0x22a
github.com/flike/kingshard/proxy/server.(*ClientConn).bindStmtArgs(0x11490000, 0x114e6ff0, 0x114f200a, 0x1, 0x9e, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	C:/Go/src/github.com/flike/kingshard/proxy/server/conn_stmt.go:350 +0xe15
github.com/flike/kingshard/proxy/server.(*ClientConn).handleStmtExecute(0x11490000, 0x114f2001, 0xa7, 0xa7, 0xa8, 0x0)
	C:/Go/src/github.com/flike/kingshard/proxy/server/conn_stmt.go:233 +0x1b1
github.com/flike/kingshard/proxy/server.(*ClientConn).dispatch(0x11490000, 0x114f2000, 0xa8, 0xa8, 0x0, 0x0)
	C:/Go/src/github.com/flike/kingshard/proxy/server/conn.go:316 +0x453
github.com/flike/kingshard/proxy/server.(*ClientConn).Run(0x11490000)
	C:/Go/src/github.com/flike/kingshard/proxy/server/conn.go:276 +0x7b
github.com/flike/kingshard/proxy/server.(*Server).onConn(0x11358ab0, 0x8cda80, 0x11400020)
	C:/Go/src/github.com/flike/kingshard/proxy/server/server.go:363 +0x287
created by github.com/flike/kingshard/proxy/server.(*Server).Run
	C:/Go/src/github.com/flike/kingshard/proxy/server/server.go:608 +0x127
" conn_id=0

**Comment by luyaotang** [comment]
测试环境：

**Comment by luyaotang** [comment]
已经解决。升级到最新的mysql-connector-java-5.1.44-bin.jar解决问题。
