### ISSUE TITLE
KingShard在关闭某一个Slave节点后，自动退出

### ISSUE THREAD

**Issue by chutian52** [flike/kingshard#479]
**系统环境**
 * go ：1.11.1
 * KingShard：master最新代码
 * MySQL: 5.7.22-log
 * Cluster
      1. Master: 10.3.5.183:3306
      2. Slave：10.3.5.184:3306@2, 10.3.5.176:3306@3

**复现步骤**
1.  启动kingshard。
```
$ /src/github.com/flike/kingshard/bin/kingshard -config=/src/github.com/flike/kingshard/etc/unshard.yaml &
```
2. 关闭184上的从节点
```
$ systemctl stop mysqld
```
3. 抛出如下异常
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5b2466]

goroutine 36 [running]:
github.com/flike/kingshard/backend.(*Conn).Close(0x0, 0x0, 0xa195e0)
	/src/github.com/flike/kingshard/backend/backend_conn.go:127 +0x26
github.com/flike/kingshard/backend.(*DB).Ping(0xc0001f60a0, 0xc000155d30, 0x2)
	/src/github.com/flike/kingshard/backend/db.go:192 +0x122
github.com/flike/kingshard/backend.(*Node).checkSlave(0xc0001e20e0)
	/src/github.com/flike/kingshard/backend/node.go:140 +0x123
github.com/flike/kingshard/backend.(*Node).CheckNode(0xc0001e20e0)
	/src/github.com/flike/kingshard/backend/node.go:57 +0x36
created by github.com/flike/kingshard/proxy/server.parseNode
	/src/github.com/flike/kingshard/proxy/server/server.go:167 +0x134
```

从错误信息上看，应该是空指针异常导致的。根据抛出异常，发现异常代码如下
```
func (db *DB) Ping() error {
	var err error
	if db.checkConn == nil {
		db.checkConn, err = db.newConn()
		if err != nil {
			db.checkConn.Close()
			db.checkConn = nil
			return err
		}
	}
	err = db.checkConn.Ping()
	if err != nil {
		db.checkConn.Close()
		db.checkConn = nil
		return err
	}
	return nil
}
```
个人推测上述的问题代码在于db.checkConn可能是个nil,在执行Close方法的时候抛出了上述异常。修改代码如下
```
func (db *DB) Ping() error {
	var err error
	if db.checkConn == nil {
		db.checkConn, err = db.newConn()
		if err != nil {
                     // 这里确保checkConn不为nil
			if db.checkConn != nil{
				db.checkConn.Close()
				db.checkConn = nil
			}
			return err
		}
	}
	err = db.checkConn.Ping()
	if err != nil {
               //同上
		if db.checkConn != nil {
			db.checkConn.Close()
			db.checkConn = nil
		}
		return err
	}
	return nil
}
```
重新编译后执行，问题解决。

**Comment by chutian52** [comment]
@flike PR needed？

**Comment by flike** [comment]
yes, and unit test need, Thanks

**Comment by chutian52** [comment]
@flike Permission denied. Or anything I didn't get?

**Comment by flike** [comment]
FYI :https://github.com/flike/kingshard/pulls

**Comment by luyaotang** [comment]
同样的问题，希望尽快修复。后台slave宕机服务就退出
