### ISSUE TITLE
crash bug when I run a insert sql

### ISSUE THREAD

**Issue by simpleton** [flike/kingshard#77]
```
2015/11/30 19:10:02 - ERROR - conn.go:[265] - [ClientConn] "Run" "runtime error: invalid memory address or nil pointer dereference" "stack=goroutine 1218 [running]:
github.com/flike/kingshard/proxy/server.(*ClientConn).Run.func1(0xc82019c540)
	/home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn.go:261 +0x12d
github.com/flike/kingshard/proxy/server.(*ClientConn).writeResultset(0xc82019c540, 0xc820330002, 0x0, 0x0, 0x0)
	/home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn_resultset.go:145 +0xe5
github.com/flike/kingshard/proxy/server.(*ClientConn).handlePrepareExec(0xc82019c540, 0x7ff2cf0a0038, 0xc8201be480, 0xc820538901, 0xf1, 0xc8200ced00, 0xd, 0xd, 0x0, 0x0)
	/home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn_stmt.go:320 +0x3d7
github.com/flike/kingshard/proxy/server.(*ClientConn).handleStmtExecute(0xc82019c540, 0xc82019c6c1, 0xb2, 0xb2, 0x0, 0x0)
	/home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn_stmt.go:242 +0xb80
github.com/flike/kingshard/proxy/server.(*ClientConn).dispatch(0xc82019c540, 0xc82019c6c1, 0xb2, 0xb2, 0x0, 0x0)
	/home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn.go:316 +0x6d1
github.com/flike/kingshard/proxy/server.(*ClientConn).Run(0xc82019c540)
	/home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/conn.go:278 +0xcd
github.com/flike/kingshard/proxy/server.(*Server).onConn(0xc820094510, 0x7ff2cf08cab8, 0xc82002a070)
	/home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/server.go:249 +0x35a
created by github.com/flike/kingshard/proxy/server.(*Server).Run
	/home/www/sites/mysql_proxy/src/github.com/flike/kingshard/proxy/server/server.go:262 +0x195
" conn_id=0
```

**Comment by flike** [comment]
Fixed, please check it.

**Comment by simpleton** [comment]
Thanks a lot.
